# Generated by Django 6.1.1 on 2026-10-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create skills and imported questions in the initial bank schema.

    The migration stores upstream question metadata and adds the index used
    when filtering practice questions by skill, grade, and status.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.PositiveSmallIntegerField(db_index=True)),
                ('learning_objective', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('grade', models.PositiveSmallIntegerField()),
                ('prompt_en', models.TextField()),
                ('prompt_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('response_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('short_text', 'Short text'), ('multiple_choice', 'Multiple choice')], max_length=32)),
                ('requested_difficulty', models.IntegerField()),
                ('assessed_difficulty', models.IntegerField(blank=True, null=True)),
                ('source_question_ids', models.JSONField()),
                ('generation_config', models.JSONField()),
                ('validation_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=16)),
                ('validation_reasons', models.JSONField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question_bank.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['skill', 'grade', 'validation_status'], name='question_selection_idx')],
            },
        ),
    ]
