# Generated by Django 6.1.1 on 2026-10-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='response_type',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'Decimal'), (3, 'Short text'), (4, 'Multiple choice')]),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='validation_status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Flagged')]),
        ),
    ]
