# Generated by Django 6.1.1 on 2026-10-04 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_answer', models.TextField()),
                ('reviewed_correct', models.BooleanField(default=None, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='question_bank.questionitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', '-created_at'], name='attempt_recent_idx'), models.Index(fields=['reviewed_correct', 'created_at'], name='attempt_review_idx')],
            },
        ),
    ]
